---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

env:
  DOCKER_CONTAINER: frankjoshua/ros-jupyter

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push image to DockerHub
        run: ./build.sh -t $DOCKER_CONTAINER -p -a linux/arm/v7,linux/arm64,linux/amd64
